server:
  port: 8080

spring:
  application:
    name: tet-train-ticket
  profiles:
    active: api
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.jdbc.autoconfigure.health.DataSourceHealthContributorAutoConfiguration
      - org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
